Document: vulkan-profiles
Title: Debian vulkan-profiles Manual
Author: <insert document author here>
Abstract: This manual describes what vulkan-profiles is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vulkan-profiles/vulkan-profiles.sgml.gz

Format: postscript
Files: /usr/share/doc/vulkan-profiles/vulkan-profiles.ps.gz

Format: text
Files: /usr/share/doc/vulkan-profiles/vulkan-profiles.text.gz

Format: HTML
Index: /usr/share/doc/vulkan-profiles/html/index.html
Files: /usr/share/doc/vulkan-profiles/html/*.html
